name: Run Scheduled Prediction

on:
  schedule:
    # 15分ごとに実行
    - cron: '*/5 * * * *'
  
  # 手動でも実行できるようにする
  workflow_dispatch:

jobs:
  run-prediction:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのコードをチェックアウト
        uses: actions/checkout@v4

      - name: Python 3.10 をセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 必要なライブラリをインストール
        run: pip install -r requirements.txt

      - name: Write Firebase credential JSON
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIAL_JSON }}" | base64 -d > firebase-key.json

      - name: 予測スクリプトを実行
        run: python run_prediction.py